CREATE DATABASE HOLYWOOD

DROP DATABASE HOLYWOOD

USE HOLYWOOD

DROP TABLE MOVIES

CREATE TABLE MOVIES
(
ID INT IDENTITY(1,1),
TITLE VARCHAR(50),
DIRECTOR VARCHAR(30)
) 

SELECT * FROM MOVIES

INSERT MOVIES(TITLE,DIRECTOR)
VALUES('Titanic','James Camron')

INSERT MOVIES(TITLE,DIRECTOR)
VALUES('Star Wars','George Lucas')

INSERT MOVIES(TITLE,DIRECTOR)
VALUES('Jurrasic Park','Steven Spielberg')

INSERT MOVIES(TITLE,DIRECTOR)
VALUES('Jaws','Steven Spielberg')

INSERT MOVIES(TITLE,DIRECTOR)
VALUES('Ghost','Jerry Zuker')

INSERT MOVIES(TITLE,DIRECTOR)
VALUES('Forrest Gump','Robert Zemeckis')

INSERT MOVIES(TITLE,DIRECTOR)
VALUES('Ice Age','Chris Wedge')

INSERT MOVIES(TITLE,DIRECTOR)
VALUES('Shrek','Andrew Ademson')

INSERT MOVIES(TITLE,DIRECTOR)
VALUES('Independence Day','Ronald Emmerich')

INSERT MOVIES(TITLE,DIRECTOR)
VALUES('The Ring','Gore Verbinski')

INSERT MOVIES(TITLE,DIRECTOR)
VALUES('Flight Plan','Bob')

