CREATE DATABASE SBIBank

USE SBIBank

DROP TABLE ACCOUNTS

CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) CONSTRAINT PK_AC_NO PRIMARY KEY,
ACCOUNT_TYPE VARCHAR(10),
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
ADDRESS VARCHAR(50),
STATE VARCHAR(40),
CITY VARCHAR(40),
BALANCE MONEY,
MOBILE VARCHAR(10),
DATE_OF_BIRTH DATETIME,
OPENING_DATE DATETIME,
EMAIL VARCHAR(80),
AC_IMAGE VARCHAR(100),
GENDER VARCHAR(10),
DEBIT_CARD BIT,
CREDIT_CARD BIT,
ONLINE_BANKING BIT
)

SELECT * FROM ACCOUNTS

INSERT ACCOUNTS(ACNO,ACCOUNT_TYPE,FIRST_NAME,LAST_NAME,ADDRESS,STATE,CITY,BALANCE,MOBILE,DATE_OF_BIRTH,OPENING_DATE,EMAIL,AC_IMAGE,GENDER,DEBIT_CARD,CREDIT_CARD,ONLINE_BANKING)
VALUES('A00001','SAVING','SUVIDHA','SHARMA','35 LALA KA BAZAR','UTTAR PRADESH','MEERUT',9000,'9837371023','08/25/1990','08/09/2016','suvidha98@gmail.com','D:\BACKUP\IMAGE\JOJN.JPG','FEMALE',1,0,1)

DELETE ACCOUNTS

SELECT ACNO FROM ACCOUNTS
