/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminFrame.java
 *
 * Created on May 15, 2011, 12:24:12 PM
 */
package onlineexam;

import javax.swing.JFrame;

/**
 *
 * @author Nagendra
 */
public class AdminFrame extends javax.swing.JFrame {
    private JFrame parent;
    /** Creates new form AdminFrame */
    public AdminFrame() {
        initComponents();
    }
    public void setParentFrame(JFrame f){
        parent = f;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageQuestionsPanel1 = new onlineexam.ManageQuestionsPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        manageQuestionsPanel2 = new onlineexam.ManageQuestionsPanel();
        addQuestionPanel1 = new onlineexam.AddQuestionPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.addTab("Manage Questions", manageQuestionsPanel2);
        jTabbedPane1.addTab("Add Question", addQuestionPanel1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private onlineexam.AddQuestionPanel addQuestionPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private onlineexam.ManageQuestionsPanel manageQuestionsPanel1;
    private onlineexam.ManageQuestionsPanel manageQuestionsPanel2;
    // End of variables declaration//GEN-END:variables
}
