/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on May 13, 2011, 6:00:56 AM
 */
package onlineexam;

import javax.swing.JFrame;

/**
 *
 * @author Nagendra
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }
    public void setChild(JFrame child) {
        this.child = child;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnRegistration = new javax.swing.JButton();
        btnExamination = new javax.swing.JButton();
        btnAdministration = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Examination System");
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblTitle.setText("Welcome to Online Examination System");

        btnRegistration.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRegistration.setText("Registration");
        btnRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationActionPerformed(evt);
            }
        });

        btnExamination.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnExamination.setText("Examination");
        btnExamination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminationActionPerformed(evt);
            }
        });

        btnAdministration.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAdministration.setText("Administration");
        btnAdministration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdministration, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(btnRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExamination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitle)
                .addGap(41, 41, 41)
                .addComponent(btnRegistration)
                .addGap(38, 38, 38)
                .addComponent(btnExamination)
                .addGap(40, 40, 40)
                .addComponent(btnAdministration)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationActionPerformed
        RegistrationFrame f = new RegistrationFrame();
        f.setLocationRelativeTo(null);
        f.setParentFrame(this);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegistrationActionPerformed

    private void btnExaminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminationActionPerformed
        LoginFrame f = new LoginFrame("exam");
        f.setLocationRelativeTo(null);
        f.setParentFrame(this);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExaminationActionPerformed

    private void btnAdministrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrationActionPerformed
        LoginFrame f = new LoginFrame("admin");
        f.setLocationRelativeTo(null);
        f.setParentFrame(this);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdministrationActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministration;
    private javax.swing.JButton btnExamination;
    private javax.swing.JButton btnRegistration;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
    private JFrame child;
}
