CREATE DATABASE SBIBank1

DROP DATABASE SBIBank1

USE SBIBank1

DROP TABLE USERS

CREATE TABLE USERS
(
UserName VARCHAR(25) PRIMARY KEY,
PASSWORD VARCHAR(25)
)

SELECT * FROM USERS

INSERT USERS(UserName,PASSWORD)
values('admin','niit007')

INSERT USERS(UserName,PASSWORD)
values('user1','user1')

DROP TABLE ACCOUNTS

CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) PRIMARY KEY,
ACCOUNT_TYPE VARCHAR(10),
CREDIT_LIMIT MONEY,
NAME VARCHAR(30),
ADDRESS VARCHAR(50),
BALANCE MONEY,
PHONE_NO VARCHAR(15),
DATE_OF_BIRTH DATETIME,
OPENING_DATE DATETIME,
AC_IMAGE VARCHAR(100)
)

SELECT * FROM ACCOUNTS

DELETE ACCOUNTS

SELECT ACNO FROM ACCOUNTS

SELECT * FROM ACCOUNTS WHERE ACNO='A00007'

SELECT max(ACNO) FROM ACCOUNTS

DROP TABLE TRANSACTIONS

DELETE TRANSACTIONS

DROP TABLE TRANSACTIONS
CREATE TABLE TRANSACTIONS
(
TRAN_ID CHAR(6) PRIMARY KEY,
ACNO CHAR(6),
TRAN_TYPE VARCHAR(10),
AMOUNT MONEY,
DOC_TYPE VARCHAR(10),
DOC_NUMBER VARCHAR(20),
TRAN_DATE DATETIME
CONSTRAINT cons_doctype_docnumber unique(DOC_TYPE,DOC_NUMBER)
)

SELECT * FROM ACCOUNTS

SELECT * FROM TRANSACTIONS  ORDER BY TRAN_ID ASC

SELECT ACNO FROM ACCOUNTS  ORDER BY ACNO ASC