
SELECT * FROM AUTHORS

SELECT * FROM TITLES

SELECT * FROM TITLEAUTHOR

SELECT * FROM SALES

SELECT * FROM DISCOUNTS

SELECT * FROM EMPLOYEE

SELECT * FROM JOBS

SELECT * FROM PUB_INFO

SELECT * FROM PUBLISHERS

SELECT * FROM ROYSCHED

SELECT * FROM AUTHORS
WHERE contract = 1

SELECT * FROM AUTHORS
WHERE contract <> 1

SELECT * FROM SALES
WHERE qty = 50

SELECT * FROM SALES
WHERE qty <> 50

SELECT * FROM SALES
WHERE qty > 50

SELECT * FROM SALES
WHERE qty >= 50

SELECT * FROM SALES
WHERE qty < 50

SELECT * FROM SALES
WHERE qty <= 50

SELECT * FROM AUTHORS
WHERE city = 'Oakland'

SELECT * FROM AUTHORS
WHERE city = 'Oakland' AND contract = 1

SELECT * FROM AUTHORS
WHERE city = 'Oakland' OR contract = 1

SELECT * FROM AUTHORS
WHERE city = 'Oakland' OR STATE = 'IN'

SELECT * FROM AUTHORS
WHERE city = 'Oakland' AND STATE = 'IN'

SELECT * FROM AUTHORS
WHERE city = 'Oakland' AND NOT STATE = 'CA'

SELECT * FROM AUTHORS
WHERE city = 'Oakland' OR NOT STATE = 'CA'

SELECT * FROM AUTHORS
WHERE city = 'Oakland' AND NOT STATE = 'CA'

SELECT * FROM PUBLISHERS
WHERE EXISTS (SELECT * FROM AUTHORS
WHERE state = 'UT' AND contract = 1)

SELECT * FROM PUBLISHERS
WHERE EXISTS (SELECT * FROM AUTHORS
WHERE state = 'UT' AND contract = 0)

SELECT * FROM PUBLISHERS
WHERE NOT EXISTS (SELECT * FROM AUTHORS
WHERE state = 'UT' AND contract = 1)

SELECT * FROM PUBLISHERS
WHERE NOT EXISTS (SELECT * FROM AUTHORS
WHERE state = 'UT' AND contract = 0)

SELECT * FROM AUTHORS
SELECT * FROM titles
SELECT * FROM TITLEAUTHOR

SELECT * FROM titles INNER JOIN TITLEAUTHOR
ON titles.title_id = TITLEAUTHOR.title_id
INNER JOIN AUTHORS 
ON  TITLEAUTHOR.au_id = AUTHORS.au_id

SELECT * FROM AUTHORS
WHERE EXISTS (SELECT * FROM titles INNER JOIN TITLEAUTHOR
ON titles.title_id = TITLEAUTHOR.title_id
WHERE TITLEAUTHOR.au_id = AUTHORS.au_id)

SELECT * FROM titles 
WHERE ytd_sales BETWEEN 1000 AND 7000

SELECT * FROM titles 
WHERE ytd_sales NOT BETWEEN 1000 AND 7000

SELECT * FROM titles 
WHERE ytd_sales NOT BETWEEN 0 AND 5000

SELECT * FROM AUTHORS
SELECT * FROM titles
SELECT * FROM TITLEAUTHOR

SELECT AU_LNAME,AU_FNAME FROM authors
WHERE au_id IN(SELECT au_id FROM TITLEAUTHOR 
WHERE ROYALTYPER = 100)

SELECT AU_LNAME,AU_FNAME FROM authors
WHERE au_id NOT IN(SELECT au_id FROM TITLEAUTHOR 
WHERE ROYALTYPER = 100)

SELECT AU_LNAME,CITY FROM authors
WHERE city <> ALL(SELECT city FROM PUBLISHERS)

SELECT AU_LNAME,CITY FROM authors
WHERE city = ALL(SELECT city FROM PUBLISHERS)

SELECT AU_LNAME,CITY FROM authors
WHERE city <> ANY(SELECT city FROM PUBLISHERS)

SELECT AU_LNAME,CITY FROM authors
WHERE city = ANY(SELECT city FROM PUBLISHERS)

SELECT * FROM authors
WHERE phone LIKE '415%'

SELECT * FROM authors
WHERE ZIP LIKE '[928]4025'

SELECT * FROM authors
WHERE ZIP LIKE '[^328]0205'

SELECT * FROM authors
WHERE ZIP LIKE '9460_'

UPDATE authors
SET contract = 1
WHERE phone LIKE '415%' 

UPDATE authors
SET contract = 1
WHERE ZIP LIKE '[928]4025'

UPDATE authors
SET contract = 1
WHERE ZIP LIKE '[^328]0205'

UPDATE authors
SET contract = 1
WHERE ZIP LIKE '9460_'

SELECT * FROM titles
WHERE price IS NULL

SELECT * FROM titles
WHERE price IS NOT NULL

SELECT ISNULL(PRICE,$0.00) FROM titles

SELECT PRICE FROM titles
WHERE price IS NULL

SELECT PRICE FROM titles
WHERE price IS NOT NULL

SELECT * FROM titles
WHERE price = 20

SELECT * FROM titles
WHERE price <> 20

SELECT * FROM AUTHORS
WHERE zip = '95128'

SELECT * FROM AUTHORS
WHERE zip <> '95128'

SELECT * FROM titles
WHERE price > 20

SELECT * FROM titles
WHERE price < 20

SELECT * FROM AUTHORS
WHERE zip > '95128'

SELECT * FROM AUTHORS
WHERE zip < '95128'

SELECT * FROM EMPLOYEE

SELECT EMP_ID,LNAME,FNAME,PUB_ID
FROM EMPLOYEE
WHERE PUB_ID = NULL

SELECT EMP_ID,LNAME,FNAME,PUB_ID
FROM EMPLOYEE
WHERE PUB_ID IS NULL

SELECT EMP_ID,LNAME,FNAME,PUB_ID
FROM EMPLOYEE
WHERE PUB_ID IS NOT NULL

SELECT * FROM titles 
WHERE ytd_sales BETWEEN 1000 AND 7000

SELECT * FROM titles 
WHERE ytd_sales NOT BETWEEN 1000 AND 7000

SELECT * FROM titles 
WHERE title_id IN('BU1032','PC8888','MC2222')

SELECT * FROM titles 
WHERE ytd_sales IN(2032,4095,375)

SELECT * FROM titles 
WHERE title_id NOT IN('BU1032','PC8888','MC2222')

SELECT * FROM titles 
WHERE ytd_sales NOT IN(2032,4095,375)

SELECT * FROM authors
WHERE phone LIKE '415%'

SELECT * FROM authors
WHERE phone NOT LIKE '415%'


SELECT * FROM authors
WHERE phone LIKE '%15%'

SELECT * FROM authors
WHERE phone LIKE '_08%'

SELECT * FROM authors
WHERE phone LIKE '7_%_%'

SELECT * FROM authors
WHERE phone LIKE '_1%3'

SELECT * FROM authors
WHERE zip LIKE '2___3'


SELECT * FROM authors
WHERE phone NOT LIKE '%15%'

SELECT * FROM authors
WHERE phone NOT LIKE '_08%'

SELECT * FROM authors
WHERE phone NOT LIKE '7_%_%'

SELECT * FROM authors
WHERE phone NOT LIKE '_1%3'

SELECT * FROM authors
WHERE zip NOT LIKE '2___3'

SELECT * FROM authors
WHERE ZIP NOT  LIKE'[928]4025'

SELECT * FROM authors
WHERE ZIP LIKE '[^328]0205'

SELECT * FROM authors
WHERE ZIP LIKE '9460_'

SELECT * FROM titles
WHERE EXISTS (SELECT * FROM titles WHERE price < 100)

SELECT * FROM titles
WHERE NOT EXISTS (SELECT * FROM titles WHERE price > 10000)

SELECT * FROM titles
WHERE EXISTS (SELECT * FROM titles WHERE price > 10000)

--28/05/2015

SELECT price FROM titles

SELECT DISTINCT price FROM titles

SELECT ALL price FROM titles

SELECT * FROM titles
WHERE price > ALL (SELECT PRICE FROM titles WHERE price < 10)

SELECT * FROM titles
WHERE price > ANY (SELECT PRICE FROM titles WHERE price < 10)

SELECT * FROM titles
WHERE price > 10 AND price < 30

SELECT * FROM titles
WHERE title_id = 'BU1111' OR title_id = 'MC2222' 

SELECT * FROM titles
WHERE title_id = 'BU1111' OR title_id = 'MC2222' OR 
title_id = 'PC1035'

SELECT * FROM titles
WHERE ytd_sales IS NULL

SELECT * FROM titles
WHERE ytd_sales IS NOT  NULL

SELECT 50 + 20

SELECT 50 - 20

SELECT 50 * 20

SELECT 50 / 20

SELECT 50 % 20

SELECT * FROM titles


SELECT price + YTD_SALES AS 'TOTAL AMOUNT' FROM titles

SELECT price FROM titles
WHERE price + YTD_SALES > 5000

SELECT  YTD_SALES - price AS 'DIFFERENCE AMOUNT' 
FROM titles

SELECT price FROM titles
WHERE YTD_SALES - price > 5000

SELECT  price * 10 AS 'PRODUCT AMOUNT' 
FROM titles

SELECT price FROM titles
WHERE price * 10 > 50

SELECT  price / 10 AS 'QUOTIENT AMOUNT' 
FROM titles

SELECT price FROM titles
WHERE price / 10 < 50

SELECT  price * 10 +1000 AS 'AMOUNT' 
FROM titles

SELECT  (price * 10) +1 000 AS 'AMOUNT' 
FROM titles
WHERE price > 20

SELECT  YTD_SALES / 52 + price
FROM titles

SELECT  YTD_SALES - 1000 + price / 52
FROM titles

SELECT (YTD_SALES - 1000 + price) / 52
FROM titles

SELECT YTD_SALES
FROM titles
WHERE YTD_SALES < PRICE * 3  + 10 / 2 - 50

SELECT * FROM titles

SELECT COUNT(*) FROM titles

SELECT COUNT(TITLE_ID) FROM titles

SELECT COUNT(YTD_SALES) FROM titles

SELECT COUNT(DISTINCT YTD_SALES) FROM titles

SELECT COUNT(ALL YTD_SALES) FROM titles

SELECT SUM(YTD_SALES) FROM titles

SELECT SUM(ALL YTD_SALES) FROM titles

SELECT SUM(DISTINCT YTD_SALES) FROM titles

SELECT AVG(YTD_SALES) FROM titles

SELECT AVG(DISTINCT YTD_SALES) FROM titles

SELECT MAX(YTD_SALES) FROM titles

SELECT MAX(DISTINCT YTD_SALES) FROM titles

SELECT MIN(YTD_SALES) FROM titles

SELECT MIN(DISTINCT YTD_SALES) FROM titles

SELECT 'BILL' + 'GATES'

SELECT 'BILL' + ' ' + 'GATES'

SELECT * FROM AUTHORS

SELECT city + STATE FROM AUTHORS

SELECT city + ' ' + STATE FROM AUTHORS

SELECT city FROM AUTHORS

SELECT TRANSLATE(city,'MBS','TVK') FROM AUTHORS

SELECT REPLACE(city,'O','S') FROM AUTHORS

SELECT REPLACE(city,'Oakland','Switzerland') FROM AUTHORS

SELECT UPPER(city) FROM AUTHORS

SELECT lower(city) FROM AUTHORS

SELECT city,SUBSTRING(city,2,5) FROM AUTHORS

SELECT SUBSTRING(city,2,5) FROM AUTHORS

SELECT * FROM AUTHORS

SELECT au_id,SUBSTRING(au_id,1,3) FROM AUTHORS

SELECT SUBSTRING(au_id,1,3) FROM AUTHORS

SELECT au_id,SUBSTRING(au_id,8,4) FROM AUTHORS

SELECT CITY FROM AUTHORS

SELECT INST(CITY,'a',1,9) FROM AUTHORS

SELECT '          MADHULIKA'

SELECT LTRIM('         MADHULIKA')

SELECT LTRIM(CITY) FROM AUTHORS

SELECT 'MADHULIKA                  '

SELECT RTRIM('MADHULIKA            ')

SELECT RTRIM(CITY) FROM AUTHORS

SELECT RTRIM(CITY,'Park') FROM AUTHORS

SELECT RTRIM(CITY) FROM AUTHORS
WHERE city = 'Oakland'

--29/05/2015

SELECT DECODE(AU_LNAME,'Dean','Straight','Not Found') 
FROM AUTHORS

SELECT LEN(AU_LNAME) FROM AUTHORS

SELECT AU_LNAME,LEN(AU_LNAME) FROM AUTHORS

SELECT * FROM TITLES

SELECT NVL(YTD_SALES,00) FROM TITLES

SELECT TITLE FROM TITLES

SELECT LPAD(TITLE,25,'*') FROM TITLES

SELECT RPAD(TITLE,25,'-') FROM TITLES

SELECT ASCII('A')

SELECT ASCII('B')

SELECT ASCII('0')

SELECT ASCII('1')

SELECT ASCII('*')

SELECT PRICE FROM TITLES

SELECT STR(PRICE) FROM TITLES

SELECT PRICE,NEW_PRICE=STR(PRICE) FROM TITLES
WHERE PRICE IS NOT NULL

SELECT * FROM AUTHORS

SELECT au_id,TO_NUMBER(au_id) FROM AUTHORS

SELECT PRICE,TO_CHAR(PRICE) FROM TITLES

SELECT AU_ID,SUBSTRING(AU_ID,2,5)
FROM AUTHORS


SELECT AU_LNAME,AU_FNAME,AU_ID,SUBSTRING(AU_ID,1,3)+' '+SUBSTRING(AU_ID,5,2)+' '+SUBSTRING(AU_ID,8,4)
FROM AUTHORS

SELECT AU_LNAME,LEN(AU_LNAME)FROM AUTHORS

SELECT LEN(AU_LNAME)+LEN(AU_FNAME)
FROM AUTHORS


SELECT AU_LNAME,AU_FNAME,LEN(AU_LNAME)+LEN(AU_FNAME)
FROM AUTHORS

SELECT GETDATE()

SELECT * FROM TITLES

datepart
Abbreviations
year
yy , yyyy
quarter
qq , q
month
mm , m
dayofyear
dy , y
day
dd , d
week
wk , ww
weekday
dw , w
hour
hh
minute
mi , n
second
ss , s
millisecond
ms
microsecond
mcs
nanosecond
ns

SELECT PUBDATE,DATEPART(mm,PUBDATE) FROM TITLES

SELECT DATEPART(dd,GETDATE())
SELECT DATEPART(mm,GETDATE())
SELECT DATEPART(yy,GETDATE())
SELECT DATEPART(dy,GETDATE()) 
SELECT DATEPART(wk,GETDATE())
SELECT DATEPART(hh,GETDATE())
SELECT DATEPART(mi,GETDATE())
SELECT DATEPART(ss,GETDATE())
SELECT DATEPART(ms,GETDATE())

SELECT DATEPART(mm,GETDATE())
SELECT DATENAME(mm,GETDATE())

SELECT DATEPART(dw,GETDATE())
SELECT DATENAME(dw,GETDATE())  

SELECT DATEADD(dd,1000,getdate())

SELECT DATEADD(mm,1,PUBDATE) FROM TITLES

SELECT PUBDATE,DATEADD(mm,1,PUBDATE) FROM TITLES

SELECT DATEDIFF(dd,'07/12/1980',GETDATE())
SELECT DATEDIFF(mm,'07/12/1980',GETDATE())
SELECT DATEDIFF(yy,'07/12/1980',GETDATE())
SELECT DATEDIFF(hh,'07/12/1980 09:55:00',GETDATE())
SELECT DATEDIFF(MI,'07/12/1980 09:55:00',GETDATE())
SELECT DATEDIFF(ss,'07/12/1980 09:55:00',GETDATE())

SELECT DATEDIFF(mm,PUBDATE,GETDATE())
FROM TITLES

SELECT title,PUBDATE,DATEDIFF(dd,PUBDATE,GETDATE())
FROM TITLES

SELECT title,PUBDATE,DATEDIFF(mm,PUBDATE,GETDATE())
FROM TITLES

SELECT title,PUBDATE,DATEDIFF(yy,PUBDATE,GETDATE())
FROM TITLES

--30/05/2015--

ELECT PUBDATE+1,PUBDATE+5 FROM TITLES
WHERE TITLE_ID = 'BU7832'



100	mon dd yyyy hh:miAM/PM (Default)
101	mm/dd/yyyy (US standard)
102	yy.mm.dd (ANSI standard)
103	dd/mm/yy (British/French standard)
104	dd.mm.yy (German standard)
105	dd-mm-yy (Italian standard)
106	dd mon yy
107	Mon dd, yy
108	hh:mi:ss
109	mon dd yyyy hh:mi:ss:mmmAM/PM
110	mm-dd-yy (USA standard)
111	yy/mm/dd (Japan standard)
112	yymmdd (ISO standard)
113	dd mon yyyy hh:mi:ss:mmm (Europe standard - 24 hour clock)
114	hh:mi:ss:mmm (24 hour clock)
120	yyyy-mm-dd hh:mi:ss (ODBC canonical - 24 hour clock)
121	yyyy-mm-dd hh:mi:ss:mmm (ODBC canonical - 24 hour clock)
126	yyyy-mm-ddThh:mi:ss:mmm (ISO8601 standard)
127	yyyy-mm-ddThh:mi:ss:mmmZ (ISO8601 standard)
130	dd mon yyyy hh:mi:ss:mmmAM/PM (Hijri standard)
131	dd/mm/yy hh:mi:ss:mmmAM/PM (Hijri standard)

SELECT CONVERT(VARCHAR(30),GETDATE(),100)

SELECT PUBDATE,DATENAME(mm,PUBDATE)
FROM TITLES

SELECT title,PUBDATE,'Month'=DATENAME(mm,PUBDATE)
FROM TITLES

SELECT title,CONVERT(VARCHAR(30),PUBDATE,100)
FROM TITLES

SELECT CONVERT(VARCHAR(30),GETDATE(),103)

SELECT PUBDATE,CONVERT(VARCHAR(30),PUBDATE,103)
FROM TITLES

SELECT PUBDATE,CONVERT(VARCHAR(50),PUBDATE,113)
FROM TITLES

SELECT CONVERT(DATETIME,'05/30/2015')

SELECT * FROM TITLES

SELECT type,SUM(advance)
FROM TITLES
GROUP BY type

SELECT type,avg(advance)
FROM TITLES
GROUP BY type


SELECT type,COUNT(advance)
FROM TITLES
GROUP BY type

SELECT type,'No fo Books'=COUNT(advance),'Total'=SUM(advance)
FROM TITLES
GROUP BY type

SELECT type
FROM TITLES

SELECT type
FROM TITLES
GROUP BY type

SELECT type,SUM(advance)
FROM TITLES
GROUP BY type
ORDER BY type ASC

SELECT type,SUM(advance)
FROM TITLES
GROUP BY type
ORDER BY type DESC

SELECT * FROM TITLES
WHERE advance > 5000

SELECT type,SUM(advance)
FROM TITLES
WHERE advance > 5000
GROUP BY type
ORDER BY type DESC

SELECT type,SUM(advance)
FROM TITLES
WHERE PRICE > 10
GROUP BY type
ORDER BY type DESC

SELECT type,SUM(advance),SUM(price)
FROM TITLES
WHERE PRICE > 10
GROUP BY type
ORDER BY type DESC

SELECT type,MIN(advance),MAX(advance),
SUM(advance),AVG(advance)
FROM TITLES
GROUP BY type

SELECT * FROM TITLES

SELECT type,pub_id,MIN(advance),MAX(advance),
SUM(advance),AVG(advance)
FROM TITLES
GROUP BY type,pub_id
ORDER BY type

SELECT type,pub_id
FROM TITLES
GROUP BY type,pub_id
ORDER BY type

SELECT SUM(advance)
FROM TITLES

SELECT SUM(advance)
FROM TITLES
GROUP BY advance

SELECT SUM(advance)
FROM TITLES
GROUP BY advance

SELECT MIN(advance),MAX(advance),
SUM(advance),AVG(advance)
FROM TITLES

SELECT * FROM AUTHORS

SELECT CITY FROM AUTHORS
GROUP BY CITY

SELECT CITY,COUNT(*) FROM AUTHORS
GROUP BY CITY

SELECT type,AVG(advance),AVG(price)
FROM TITLES
GROUP BY type

SELECT type,AVG(advance),AVG(price)
FROM TITLES
WHERE type IN('business','psychology','trad_cook')
GROUP BY type

SELECT type,AVG(advance),AVG(pri ce)
FROM TITLES
WHERE type IN('business','psychology','trad_cook')
GROUP BY type
ORDER BY 2,3 --COLUMN NO. AVG(advance),AVG(price)

SELECT type,SUM(advance)
FROM TITLES
GROUP BY type
HAVING SUM(advance) > 5000


SELECT type,SUM(advance)
FROM TITLES
WHERE advance > 400
GROUP BY type

SELECT type,SUM(advance)
FROM TITLES
WHERE advance > 400
GROUP BY type
HAVING SUM(advance) > 5000
ORDER BY type

SELECT type,SUM(advance)
FROM TITLES
WHERE type <> 'psychology'
GROUP BY type
HAVING SUM(advance) > 5000
ORDER BY 2

SELECT * FROM AUTHORS

SELECT * FROM TITLES

SELECT * FROM PUBLISHERS

SELECT * FROM TITLEAUTHOR

SELECT * FROM SALES

SELECT * FROM DISCOUNTS

SELECT * FROM EMPLOYEE

SELECT * FROM TITLES

SELECT * FROM PUBLISHERS

SELECT title_id,title,price,PUBLISHERS.pub_id,
pub_name,city 
FROM TITLES JOIN PUBLISHERS
ON PUBLISHERS.pub_id = TITLES.pub_id

SELECT title_id,title,price,PUBLISHERS.pub_id,
pub_name,city 
FROM TITLES JOIN PUBLISHERS
ON PUBLISHERS.pub_id = TITLES.pub_id
WHERE price > 20

SELECT title_id,title,price,PUBLISHERS.pub_id,
pub_name,city 
FROM TITLES INNER JOIN PUBLISHERS
ON PUBLISHERS.pub_id = TITLES.pub_id

SELECT title_id,title,price,PUBLISHERS.pub_id,
pub_name,city 
FROM TITLES INNER JOIN PUBLISHERS
ON PUBLISHERS.pub_id = TITLES.pub_id
WHERE price > 20

SELECT * FROM TITLES
JOIN PUBLISHERS
ON PUBLISHERS.pub_id = TITLES.pub_id

SELECT TITLES.*,
PUBLISHERS.pub_name,PUBLISHERS.city 
FROM TITLES JOIN PUBLISHERS
ON PUBLISHERS.pub_id = TITLES.pub_id

SELECT TIT.*,PUB.pub_id,
PUB.pub_name,PUB.city 
FROM TITLES TIT JOIN PUBLISHERS PUB
ON PUB.pub_id = TIT.pub_id

SELECT TIT.*,PUB.pub_id,
PUB.pub_name,PUB.city 
FROM TITLES TIT JOIN PUBLISHERS PUB
ON PUB.pub_id = TIT.pub_id
WHERE price > 20

SELECT * FROM TITLES
PUBLISHERS

SELECT * FROM TITLES
JOIN PUBLISHERS
ON PUBLISHERS.pub_id = TITLES.pub_id

SELECT * FROM TITLES

SELECT * FROM PUBLISHERS

SELECT title_id,title,price,PUBLISHERS.pub_id,
pub_name,city 
FROM TITLES JOIN PUBLISHERS
ON PUBLISHERS.pub_id = TITLES.pub_id

SELECT title_id,title,price,PUBLISHERS.pub_id,
pub_name,city 
FROM TITLES JOIN PUBLISHERS
ON PUBLISHERS.pub_id != TITLES.pub_id

SELECT title_id,title,price,PUBLISHERS.pub_id,
pub_name,city 
FROM TITLES LEFT OUTER JOIN PUBLISHERS
ON PUBLISHERS.pub_id = TITLES.pub_id

SELECT title_id,title,price,PUBLISHERS.pub_id,
pub_name,city 
FROM TITLES RIGHT OUTER JOIN PUBLISHERS
ON PUBLISHERS.pub_id = TITLES.pub_id

SELECT title_id,title,price,PUBLISHERS.pub_id,
pub_name,city 
FROM TITLES FULL OUTER JOIN PUBLISHERS
ON PUBLISHERS.pub_id = TITLES.pub_id

SELECT T1.title_id,T1.title,T1.price,T1.ytd_sales
FROM TITLES T1 JOIN TITLES T2
ON T1.advance = T2.ytd_sales

SELECT * FROM TITLES

SELECT * FROM SALES

SELECT TITLES.title_id,title,price,
stor_id,ord_num,ord_Date,qty
FROM TITLES JOIN SALES
ON TITLES.title_id = SALES.title_id AND
TITLES.ytd_sales = SALES.qty

SELECT * FROM AUTHORS

SELECT * FROM TITLES

SELECT * FROM PUBLISHERS

SELECT AUTHORS.au_id,AU_LNAME,AU_FNAME,
TITLES.title_id,title,price,
au_ord,royaltyper
FROM AUTHORS JOIN TITLEAUTHOR
ON AUTHORS.au_id = TITLEAUTHOR.au_id
JOIN TITLES
ON TITLES.title_id = TITLEAUTHOR.title_id

SELECT title_id,title,price,
PUBLISHERS.pub_id,pub_name,city 
FROM TITLES ,PUBLISHERS

SELECT * FROM TITLES

SELECT * FROM PUBLISHERS

SELECT pub_id,pub_name,city
FROM PUBLISHERS
WHERE pub_id IN (SELECT pub_id FROM TITLES)

SELECT pub_id,pub_name,city
FROM PUBLISHERS
WHERE pub_id NOT IN (SELECT pub_id FROM TITLES)

SELECT * FROM TITLES

SELECT * FROM SALES

SELECT T.title_id,T.title,T.ytd_sales
FROM TITLES T
WHERE T.ytd_sales = (SELECT SUM(qty) FROM sales
					WHERE title_id = 'BU1032')
					
SELECT T.title_id,T.title,T.ytd_sales
FROM TITLES T
WHERE T.ytd_sales < (SELECT SUM(qty) FROM sales
					WHERE title_id = 'BU1032')
					
SELECT T.title_id,T.title,T.ytd_sales
FROM TITLES T
WHERE T.ytd_sales > (SELECT SUM(qty) FROM sales
					WHERE title_id = 'BU1032')
					
				
SELECT * FROM TITLES

SELECT * FROM PUBLISHERS

SELECT * FROM SALES
					
SELECT T.title_id,T.title,T.ytd_sales,
P.PUB_ID,P.PUB_NAME,P.CITY
FROM TITLES T JOIN PUBLISHERS P
ON T.PUB_ID = P.PUB_ID
WHERE T.ytd_sales > (SELECT SUM(qty) FROM sales
					WHERE title_id = 'BU1032')

SELECT * FROM TITLES	
				
SELECT * INTO MY_TITLE
FROM TITLES

SELECT * FROM MY_TITLE

DELETE MY_TITLE

INSERT INTO MY_TITLE
SELECT T.title_id,title,type,pub_id,price,advance ,
royalty,ytd_sales,notes,pubdate
FROM titles T JOIN sales S  
on T.title_id = S.title_id
WHERE T.ytd_sales > (SELECT SUM(qty) FROM sales
					WHERE title_id = 'BU1032')
					
--02/06/2015--

SELECT * FROM TITLES

SELECT * FROM SALES
					
UPDATE TITLES
SET PRICE = PRICE + (PRICE*1/100)
WHERE title_id IN(SELECT title_id from sales where qty > 10)

DELETE TITLES
WHERE title_id 
IN (SELECT title_id from sales where qty < 5)

SELECT * FROM TITLES

SELECT * FROM TITLEAUTHOR

SELECT * FROM AUTHORS

--  NESTED SUB QUERY
					
SELECT TITLE_ID,TITLE,PRICE
FROM TITLES
WHERE TITLE_ID IN
 (SELECT TITLE_ID FROM TITLEAUTHOR 
  WHERE au_id IN
  (SELECT au_id FROM AUTHORS 
   WHERE au_lname = 'White' AND au_fname = 'Johnson')) 
   
SELECT * FROM TITLES

SELECT * FROM SALES

-- Corelated subquery 
  
SELECT TITLE_ID,TITLE,PRICE,ytd_sales
FROM TITLES TIT
WHERE ytd_sales >
 (SELECT SUM(qty) from sales SAL 
   WHERE TIT.TITLE_ID = SAL.TITLE_ID)
   
SELECT * FROM TITLES

SELECT ADVANCE FROM TITLES

SELECT AVG(ADVANCE) FROM TITLES

SELECT AVG(DISTINCT ADVANCE) FROM TITLES

SELECT CITY FROM AUTHORS

SELECT COUNT(CITY) FROM AUTHORS

SELECT COUNT(DISTINCT CITY) FROM AUTHORS

SELECT MAX(ADVANCE) FROM TITLES

SELECT MIN(YTD_SALES) FROM TITLES

SELECT SUM(ADVANCE) FROM TITLES

SELECT STDEV(YTD_SALES) FROM TITLES

SELECT STDEVP(YTD_SALES) FROM TITLES

SELECT VAR(YTD_SALES) FROM TITLES

SELECT VARP(YTD_SALES) FROM TITLES


SELECT DATEADD(dd,1000,getdate())

SELECT DATEADD(mm,1,PUBDATE) FROM TITLES

SELECT DAY(GETDATE())

SELECT MONTH(GETDATE())

SELECT YEAR(GETDATE())

SELECT ABS(-65)

SELECT ABS(65)

SELECT ACOS(-1.00)

SELECT ASIN(-1.00)

SELECT ATAN(-35.00)

SELECT ATN2(35.1,138)

SELECT CEILING(12.87)

SELECT COS(12.3)

SELECT COT(12.3)

SELECT DEGREES(12.3)

SELECT EXP(12.3)

SELECT FLOOR(12.87)

SELECT LOG(3.14)

SELECT PI()

SELECT POWER(2,5)

SELECT RADIANS(45)

SELECT RAND(5)

SELECT ROUND(568.247,2)

SELECT SIGN(200)

SELECT SIN(568.24)

SELECT SIN(568.24)





















































