CREATE DATABASE SBI
go

DROP DATABASE SBI

USE SBI

CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(15) NOT NULL,
MIDDLE_NAME VARCHAR(15) NULL,
LAST_NAME VARCHAR(15) NOT NULL,
ADDRESS VARCHAR(80) NOT NULL,
CITY VARCHAR(30) NOT NULL,
PIN_CODE CHAR(6),
STATE VARCHAR(25) NOT NULL,
BIRTH_DATE DATETIME NOT NULL,
PHONE_NO VARCHAR(15),
BALANCE MONEY NOT NULL,
OPENING_DATE DATETIME NOT NULL
)

DROP TABLE ACCOUNTS

CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
ADDRESS VARCHAR(80) NOT NULL,
CITY VARCHAR(30) NOT NULL,
PIN_CODE CHAR(6),
STATE VARCHAR(25) NOT NULL,
COUNTRY VARCHAR(30) NOT NULL,
GENDER CHAR(6),
BIRTH_DATE DATETIME NOT NULL,
PHONE_NO VARCHAR(15),
BALANCE MONEY NOT NULL,
OPENING_DATE DATETIME NOT NULL,
ONLINE_BANKING BIT,
DEBIT_CARD BIT
)

DROP TABLE ACCOUNTS

SELECT * FROM ACCOUNTS

INSERT ACCOUNTS(ACNO,FIRST_NAME,MIDDLE_NAME,LAST_NAME,ADDRESS,CITY,PIN_CODE,STATE,BIRTH_DATE,PHONE_NO,BALANCE,OPENING_DATE)
VALUES('A00001','AJAY','KUMAR','SHARMA','33 D SAKET','MEERUT','250001','UTTAR PRADESH','08/22/1980','9837371123',15000.00,'04/15/2015')

INSERT ACCOUNTS(ACNO,FIRST_NAME,MIDDLE_NAME,LAST_NAME,ADDRESS,CITY,PIN_CODE,STATE,BIRTH_DATE,PHONE_NO,BALANCE,OPENING_DATE)
VALUES('A00002','VIJAY','KUMAR','SHARMA','34 D SAKET','MEERUT','250001','UTTAR PRADESH','11/24/1982','9837371155',11000.00,'04/15/2015')

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,ADDRESS,CITY,STATE,BIRTH_DATE,PHONE_NO,BALANCE,OPENING_DATE)
VALUES('A00003','REEMA','SHARMA','67 D SHASHTRI NAGAR','MEERUT','UTTAR PRADESH','12/27/1990','8837371155',16000.00,'04/15/2015')

INSERT ACCOUNTS
VALUES('A00004','SEEMA',NULL,'BHARDWAJ','11 RAJPUR ROAD','DEHRADUN','248179','UTTARAKHAND','01/24/1982','8856371155',9000.00,'04/15/2015')

SELECT ACNO,FIRST_NAME,LAST_NAME,BALANCE
FROM ACCOUNTS

SELECT ACNO,FIRST_NAME,LAST_NAME,BALANCE
FROM ACCOUNTS
WHERE ACNO = 'A00002'

SELECT * FROM ACCOUNTS
WHERE ACNO = 'A00002'

SELECT * FROM ACCOUNTS
WHERE BALANCE > 10000

SELECT * FROM ACCOUNTS
WHERE CITY = 'DEHRADUN'

SELECT * FROM ACCOUNTS
WHERE BALANCE >= 15000

SELECT * FROM ACCOUNTS

UPDATE ACCOUNTS
SET LAST_NAME = 'BHARDWAJ'
WHERE ACNO = 'A00003'

UPDATE ACCOUNTS
SET ADDRESS = '45 LAJPAT NAGAR',CITY = 'DELHI',STATE = 'DELHI',PIN_CODE = '110009'
WHERE ACNO = 'A00003'

UPDATE ACCOUNTS
SET BALANCE = 4000

UPDATE ACCOUNTS
SET BALANCE = 25000
WHERE ACNO = 'A00003'

SELECT * FROM ACCOUNTS

DELETE ACCOUNTS

DELETE ACCOUNTS
WHERE ACNO = 'A00002'

SELECT * FROM ACCOUNTS

DROP TABLE TRANSACTIONS

CREATE TABLE TRANSACTIONS
(
TRAN_ID CHAR(8) NOT NULL PRIMARY KEY,
ACNO CHAR(6) NOT NULL FOREIGN KEY REFERENCES ACCOUNTS(ACNO),
AMOUNT MONEY NOT NULL,
TRAN_DATE DATETIME NOT NULL,
TRAN_TYPE VARCHAR(15) NOT NULL
)

SELECT * FROM ACCOUNTS

SELECT * FROM TRANSACTIONS

INSERT TRANSACTIONS(TRAN_ID,ACNO,AMOUNT,TRAN_DATE,TRAN_TYPE)
VALUES('T0000001','A00001',2000.00,'04/16/2015','DEPOSIT')

UPDATE ACCOUNTS
SET BALANCE = BALANCE + 2000.00
WHERE ACNO = 'A00001'

INSERT TRANSACTIONS(TRAN_ID,ACNO,AMOUNT,TRAN_DATE,TRAN_TYPE)
VALUES('T0000002','A00002',500.00,'04/16/2015','WITHDRAWL')

UPDATE ACCOUNTS
SET BALANCE = BALANCE - 500.00
WHERE ACNO = 'A00002'

INSERT TRANSACTIONS(TRAN_ID,ACNO,AMOUNT,TRAN_DATE,TRAN_TYPE)
VALUES('T0000003','A00002',3000.00,'04/16/2015','DEPOSIT')

UPDATE ACCOUNTS
SET BALANCE = BALANCE + 3000.00
WHERE ACNO = 'A00002'

SELECT * FROM ACCOUNTS


SELECT ACNO,BALANCE FROM ACCOUNTS
WHERE ACNO = 'A00002'

SELECT * FROM TRANSACTIONS

DROP TABLE FRIENDS 

CREATE TABLE FRIENDS 
(
FRIEND_ID INT PRIMARY KEY,
FRIEND_NAME  VARCHAR(50),
ADDRESS VARCHAR(50)
)
-- PRIMARY APPLY UNIQUE CLUSTERED INDEX
--CLUSTERED INDEX DO SORTING
CREATE TABLE FRIENDS 
(
FRIEND_ID INT IDENTITY(101,1) PRIMARY KEY,
FRIEND_NAME  VARCHAR(50),
ADDRESS VARCHAR(50)
)




CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) NOT NULL PRIMARY KEY CLUSTERED,
FIRST_NAME VARCHAR(15) NOT NULL,
MIDDLE_NAME VARCHAR(15) NULL,
LAST_NAME VARCHAR(15) NOT NULL,
ADDRESS VARCHAR(80) NOT NULL,
CITY VARCHAR(30) NOT NULL DEFAULT 'MEERUT',
PIN_CODE CHAR(6) DEFAULT '250002',
STATE VARCHAR(25) NOT NULL,
BIRTH_DATE DATETIME NOT NULL,
PHONE_NO VARCHAR(15),
BALANCE MONEY NOT NULL DEFAULT 5000,
OPENING_DATE DATETIME NOT NULL DEFAULT GETDATE()
)

SELECT GETDATE()

DROP TABLE ACCOUNTS

SELECT * FROM ACCOUNTS

INSERT ACCOUNTS(ACNO,FIRST_NAME,MIDDLE_NAME,LAST_NAME,ADDRESS,STATE,BIRTH_DATE,PHONE_NO)
VALUES('A00001','AJAY','KUMAR','SHARMA','33 D SAKET','UTTAR PRADESH','08/22/1980','9837371123')

INSERT ACCOUNTS(ACNO,FIRST_NAME,MIDDLE_NAME,LAST_NAME,ADDRESS,CITY,PIN_CODE,STATE,BIRTH_DATE,PHONE_NO,BALANCE,OPENING_DATE)
VALUES('A00002','VIJAY','KUMAR','SHARMA','34 D SAKET','DELHI','250001','UTTAR PRADESH','11/24/1982','9837371155',11000.00,'04/15/2015')

CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) NOT NULL PRIMARY KEY CLUSTERED,
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
BALANCE MONEY NOT NULL DEFAULT 5000,
)

DROP TABLE ACCOUNTS

SELECT * FROM ACCOUNTS

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00001','AJAY','SHARMA',5000.00)

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00002','JOY','JULIAN',9000.00)

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00003','VINITA','JAIN',2000.00)

CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) NOT NULL UNIQUE CLUSTERED,
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
BALANCE MONEY NOT NULL DEFAULT 5000,
)

DROP TABLE ACCOUNTS

SELECT * FROM ACCOUNTS

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00001','AJAY','SHARMA',5000.00)

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00002','JOY','JULIAN',9000.00)

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00003','VINITA','JAIN',2000.00)


CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) NOT NULL UNIQUE NONCLUSTERED,
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
BALANCE MONEY NOT NULL DEFAULT 5000,
)

DROP TABLE ACCOUNTS

SELECT * FROM ACCOUNTS

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00001','AJAY','SHARMA',5000.00)

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00002','JOY','JULIAN',9000.00)

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00003','VINITA','JAIN',2000.00)


CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) NOT NULL,
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
BALANCE MONEY NOT NULL DEFAULT 5000,
)

CREATE NONCLUSTERED INDEX INDEX_ACNO
ON
ACCOUNTS(ACNO)

CREATE CLUSTERED INDEX INDEX_ACNO
ON
ACCOUNTS(ACNO)

CREATE UNIQUE CLUSTERED INDEX INDEX_ACNO
ON
ACCOUNTS(ACNO)

CREATE NONCLUSTERED INDEX INDEX_ACNO
ON
ACCOUNTS(ACNO)

DROP INDEX ACCOUNTS.INDEX_ACNO

DROP TABLE ACCOUNTS

SELECT * FROM ACCOUNTS

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00001','AJAY','SHARMA',5000.00)

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00002','JOY','JULIAN',9000.00)

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE)
VALUES('A00003','VINITA','JAIN',2000.00)


DROP TABLE ACCOUNTS
--CONSTRAINT CHECK_ACNO CHECK(ACNO LIKE 'A[A-C][0-9][0-9][0-9][A-Z]'),
CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) NOT NULL CONSTRAINT PK_ACNO PRIMARY KEY CLUSTERED
CONSTRAINT CHECK_ACNO CHECK(ACNO LIKE 'A[0-9][0-9][0-9][0-9][0-9]'),
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
BALANCE MONEY NOT NULL DEFAULT  ,
AC_TYPE VARCHAR(15) CONSTRAINT CHECK_AC_TYPE CHECK(AC_TYPE IN('SAVING','CURRENT')) 
)

SELECT * FROM ACCOUNTS

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE,AC_TYPE)
VALUES('A00001','AJAY','SHARMA',5000.00,'SAVING')

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE,AC_TYPE)
VALUES('A00002','JOY','JULIAN',9000.00,'CURRENT')

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE,AC_TYPE)
VALUES('A00003','VINITA','JAIN',2000.00,'NOTHING')

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE,AC_TYPE)
VALUES('T00001','VINITA','JAIN',2000.00,'SAVING')

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE,AC_TYPE)
VALUES('A001','AJAY','SHARMA',5000.00,'SAVING')


DROP TABLE TRANSACTIONS

SELECT * FROM ACCOUNTS

CREATE TABLE TRANSACTIONS
(
TRAN_ID CHAR(8) NOT NULL PRIMARY KEY,
ACNO CHAR(6) NOT NULL CONSTRAINT FK_ACNO FOREIGN KEY REFERENCES ACCOUNTS(ACNO),
AMOUNT MONEY NOT NULL,
TRAN_DATE DATETIME NOT NULL,
TRAN_TYPE VARCHAR(15) NOT NULL CONSTRAINT CHK_TRAN_TYPE CHECK(TRAN_TYPE IN('DEPOSIT','WITHDRAWL'))
)

SELECT * FROM ACCOUNTS

SELECT * FROM TRANSACTIONS

INSERT TRANSACTIONS(TRAN_ID,ACNO,AMOUNT,TRAN_DATE,TRAN_TYPE)
VALUES('T0000001','A00001',2000.00,'04/16/2015','DEPOSIT')

UPDATE ACCOUNTS
SET BALANCE = BALANCE + 2000.00
WHERE ACNO = 'A00001'

INSERT TRANSACTIONS(TRAN_ID,ACNO,AMOUNT,TRAN_DATE,TRAN_TYPE)
VALUES('T0000002','A00002',500.00,'04/16/2015','WITH')

DROP TABLE TRANSACTIONS

CREATE TABLE TRANSACTIONS
(
TRAN_ID CHAR(8) NOT NULL PRIMARY KEY,
ACNO CHAR(6) NOT NULL CONSTRAINT FK_ACNO FOREIGN KEY REFERENCES ACCOUNTS(A NO),
AMOUNT MONEY NOT NULL,
TRAN_DATE DATETIME NOT NULL,
TRAN_TYPE VARCHAR(15) NOT NULL
)
 
SELECT * FROM ACCOUNTS

SELECT * FROM TRANSACTIONS

INSERT TRANSACTIONS(TRAN_ID,ACNO,AMOUNT,TRAN_DATE,TRAN_TYPE)
VALUES('T0000001','A00001',2000.00,'04/16/2015','DEPOSIT')

UPDATE ACCOUNTS
SET BALANCE = BALANCE + 2000.00
WHERE ACNO = 'A00001'

INSERT TRANSACTIONS(TRAN_ID,ACNO,AMOUNT,TRAN_DATE,TRAN_TYPE)
VALUES('T0000003','A00002',700.00,'04/16/2015','WITHDRAWL')


CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) NOT NULL CONSTRAINT PK_ACNO PRIMARY KEY CLUSTERED
CONSTRAINT CHECK_ACNO CHECK(ACNO LIKE 'A[0-9][0-9][0-9][0-9][0-9]'),
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
BALANCE MONEY NOT NULL DEFAULT  ,
AC_TYPE VARCHAR(15) CONSTRAINT CHECK_AC_TYPE CHECK(AC_TYPE IN('SAVING','CURRENT')) 
)

SELECT * FROM ACCOUNTS

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE,AC_TYPE)
VALUES('A00001','AJAY','SHARMA',5000.00,'SAVING')

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE,AC_TYPE)
VALUES('A00002','JOY','JULIAN',9000.00,'CURRENT')

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE,AC_TYPE)
VALUES('A00003','VINITA','JAIN',2000.00,'NOTHING')

ALTER TABLE ACCOUNTS
ADD OPENING_DATE DATETIME 

ALTER TABLE ACCOUNTS
DROP COLUMN OPENING_DATE

UPDATE ACCOUNTS
SET OPENING_DATE = '04/18/2015'
WHERE ACNO = 'A00001'

DROP TABLE TRANSACTIONS 

DROP TABLE DBO.ACCOUNTS 

CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) NOT NULL CONSTRAINT PK_ACNO PRIMARY KEY CLUSTERED
CONSTRAINT CHECK_ACNO CHECK(ACNO LIKE 'A[0-9][0-9][0-9][0-9][0-9]'),
FIRST_NAME VARCHAR(15) NOT NULL,
LAST_NAME VARCHAR(15) NOT NULL,
BALANCE MONEY NOT NULL DEFAULT  500 CONSTRAINT CHK_BALENCE CHECK(BALANCE >=0),
AC_TYPE VARCHAR(15) CONSTRAINT CHECK_AC_TYPE CHECK(AC_TYPE IN('SAVING','CURRENT')),
PHONE_NO VARCHAR(15) NULL CONSTRAINT CHK_PHONE CHECK(PHONE_NO LIKE '([0-9][0-9][0-9])-[0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
ONLINE_BANKING BIT 
)

SELECT * FROM ACCOUNTS

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE,AC_TYPE,PHONE_NO,ONLINE_BANKING)
VALUES('A00001','AJAY','SHARMA',5000.00,'SAVING','(121)-2657789',1)


INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,BALANCE,AC_TYPE,PHONE_NO,ONLINE_BANKING)
VALUES('A00002','JAY','SHARMA',200.00,'SAVING',1212421167,1)



INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,AC_TYPE,PHONE_NO,ONLINE_BANKING)
VALUES('A00003','JAY','SHARMA','SAVING',NULL,1)


CREATE TABLE ACCOUNTS
(
ACNO CHAR(6) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(15) NOT NULL,
MIDDLE_NAME VARCHAR(15) NULL,
LAST_NAME VARCHAR(15) NOT NULL,
ADDRESS VARCHAR(80) NOT NULL,
CITY VARCHAR(30) NOT NULL,
PIN_CODE CHAR(6),
STATE VARCHAR(25) NOT NULL,
BIRTH_DATE DATETIME NOT NULL,
PHONE_NO VARCHAR(15),
BALANCE MONEY NOT NULL,
OPENING_DATE DATETIME NOT NULL
)

DROP TABLE ACCOUNTS

SELECT * FROM ACCOUNTS

INSERT ACCOUNTS(ACNO,FIRST_NAME,MIDDLE_NAME,LAST_NAME,ADDRESS,CITY,PIN_CODE,STATE,BIRTH_DATE,PHONE_NO,BALANCE,OPENING_DATE)
VALUES('A00001','AJAY','KUMAR','SHARMA','33 D SAKET','MEERUT','250001','UTTAR PRADESH','08/22/1980','9837371123',15000.00,'04/15/2015')

INSERT INTO ACCOUNTS(ACNO,FIRST_NAME,MIDDLE_NAME,LAST_NAME,ADDRESS,CITY,PIN_CODE,STATE,BIRTH_DATE,PHONE_NO,BALANCE,OPENING_DATE)
VALUES('A00002','VIJAY','KUMAR','SHARMA','34 D SAKET','MEERUT','250001','UTTAR PRADESH','11/24/1982','9837371155',11000.00,'04/15/2015')

INSERT ACCOUNTS(ACNO,FIRST_NAME,LAST_NAME,ADDRESS,CITY,STATE,BIRTH_DATE,PHONE_NO,BALANCE,OPENING_DATE)
VALUES('A00003','REEMA','SHARMA','67 D SHASHTRI NAGAR','MEERUT','UTTAR PRADESH','12/27/1990','8837371155',16000.00,'04/15/2015')

INSERT ACCOUNTS
VALUES('A00004','SEEMA',NULL,'BHARDWAJ','11 RAJPUR ROAD','DEHRADUN','248179','UTTARAKHAND','01/24/1982','8856371155',9000.00,'04/15/2015')

CREATE TABLE TRANSACTIONS
(
TRAN_ID CHAR(8) NOT NULL PRIMARY KEY,
ACNO CHAR(6) NOT NULL FOREIGN KEY REFERENCES ACCOUNTS(ACNO),
AMOUNT MONEY NOT NULL,
TRAN_DATE DATETIME NOT NULL,
TRAN_TYPE VARCHAR(15) NOT NULL
)

SELECT * FROM ACCOUNTS

SELECT * FROM TRANSACTIONS

INSERT TRANSACTIONS(TRAN_ID,ACNO,AMOUNT,TRAN_DATE,TRAN_TYPE)
VALUES('T0000001','A00001',2000.00,'04/16/2015','DEPOSIT')

UPDATE ACCOUNTS
SET BALANCE = BALANCE + 2000.00
WHERE ACNO = 'A00001'

INSERT TRANSACTIONS(TRAN_ID,ACNO,AMOUNT,TRAN_DATE,TRAN_TYPE)
VALUES('T0000002','A00002',500.00,'04/16/2015','WITHDRAWL')

UPDATE ACCOUNTS
SET BALANCE = BALANCE - 500.00
WHERE ACNO = 'A00002'

INSERT TRANSACTIONS(TRAN_ID,ACNO,AMOUNT,TRAN_DATE,TRAN_TYPE)
VALUES('T0000003','A00002',3000.00,'04/16/2015','DEPOSIT')